# このファイルは GitHub Actions のマトリックスを生成します。
# シンプルな board + shield の組み合わせの場合は、上位の board と
# shield 配列に追加してください。より細かく制御したい場合は、
# 個別の board + shield の組み合わせを `include` プロパティに追加します。
# また、`cmake-args` プロパティを使ってビルドコマンドにフラグを渡したり、
# `snippet` を使って Zephyr のスニペットを追加したり、
# `artifact-name` を使ってビルド成果物を区別する名前を割り当てることもできます。
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#

---
board: [ "nice_nano" ]
shield: [ "quadpad" ]
