# マウス機能を有効化（これがないと MS_WH_UP がエラーになります）
CONFIG_ZMK_MOUSE=y

# エンコーダーを有効化
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 名前とリセット設定
CONFIG_ZMK_KEYBOARD_NAME="SCROLL_UNIT"
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
